from datetime import datetime
from backtester.settings import get, resolve_run_id, CONFIG
from backtester.data import load_bars
from backtester.engine import run_symbol
from backtester.grid import rsi_param_grid
from backtester.results import write_metrics_csv
from backtester.benchmarks import load_benchmark, buy_hold_equity, equity_from_returns
from backtester.metrics import kpis_from_equity, summarize_comparisons, get_benchmark_equity, get_buyhold_equity
from backtester.portfolio_engine import simulate_portfolio
from backtester.data import get_data
import backtester.db as bt_db
import os
import json

def _bool(v, default=False):
    """Convert config value to bool."""
    if isinstance(v, bool):
        return v
    if isinstance(v, str):
        return v.lower() in ("true", "1", "yes", "on")
    return bool(v) if v is not None else default

def main():
    run_id = resolve_run_id()

    # Determine mode early
    is_portfolio = bool(get("PORTFOLIO_MODE", False) and not get("PORTFOLIO_USE_PARAM_GRID", False))
    mode = "portfolio" if is_portfolio else "single"

    # --- DB init (single place) ---
    db_file = None
    if get("SAVE_DB", False):
        db_file = bt_db.init_db(get("DB_PATH", "./results/db"))
        bt_db.ensure_run(db_file, run_id, mode, get("NOTES", ""))

    if is_portfolio:
        print(f"Portfolio Mode (strategies) | Run ID: {run_id}")

        def adapter(sym, start=None, end=None):
            return get_data(sym, start=start, end=end)

        result = simulate_portfolio(adapter)

        # Calculate effective weights (fallback equal weight)
        weights_eff = get("PORTFOLIO_WEIGHTS", None)
        if not weights_eff:
            tlist = get("TICKERS", [])
            if tlist:
                weights_eff = {t: 1 / len(tlist) for t in tlist}
            else:
                weights_eff = {}

        # --- DB persistence (portfolio) ---
        if db_file:
            # Serialize equity curves for tearsheet generation
            equity_json = result.equity.to_json(orient='split', date_format='iso')
            buyhold_json = None
            if result.buyhold_equity is not None:
                buyhold_json = result.buyhold_equity.to_json(orient='split', date_format='iso')
            per_ticker_json = None
            if result.per_ticker_equity:
                # Convert dict of series to JSON
                per_ticker_json = json.dumps({
                    ticker: eq.to_json(orient='split', date_format='iso')
                    for ticker, eq in result.per_ticker_equity.items()
                })
            
            # Save benchmark equity for portfolio
            if result.benchmark_equity is not None:
                bench_json = result.benchmark_equity.to_json(orient='split', date_format='iso')
                config_json = json.dumps(CONFIG, default=str)
                bt_db.update_run_benchmark(db_file, run_id, bench_json, config_json)
            
            bt_db.insert_portfolio_metrics(
                db_file, run_id, result.metrics,
                equity_json=equity_json,
                buyhold_equity_json=buyhold_json,
                per_ticker_equity_json=per_ticker_json
            )
            bt_db.insert_portfolio_weights(db_file, run_id, weights_eff)
            if get("SAVE_TRADES", True):
                bt_db.insert_trades(db_file, run_id, result.trades)

        # Portfolio tearsheets are generated by frontend on-demand

        if db_file:
            bt_db.finalize_run(db_file, run_id)
        return

    # ----- SINGLE STRATEGY MODE -----
    symbols = list(get("TICKERS"))
    dfs = load_bars(symbols)
    params_list = rsi_param_grid(CONFIG)
    print(f"Run ID: {run_id} | Grid size: {len(params_list)}")

    bench_eq_full = get_benchmark_equity()
    
    # Save benchmark equity to DB for tearsheet generation
    if db_file and bench_eq_full is not None:
        bench_eq_full.name = f"Benchmark ({get('BENCHMARK_SYMBOL', 'SPY')})"
        bench_json = bench_eq_full.to_json(orient='split', date_format='iso')
        config_json = json.dumps(CONFIG, default=str)
        bt_db.update_run_benchmark(db_file, run_id, bench_json, config_json)

    for sym in symbols:
        df = dfs[sym]
        recs = []
        bh_eq_full = get_buyhold_equity(df["Close"])
        if bh_eq_full is not None:
            bh_eq_full.name = f"{sym} Buy & Hold"

        for params in params_list:
            res = run_symbol(
                df,
                rsi_period=params["rsi_period"],
                rsi_buy_below=params["rsi_buy_below"],
                rsi_sell_above=params["rsi_sell_above"],
            )
            m = res["metrics"]
            strat_eq = res["equity"]
            events = res.get("events")
            extras = summarize_comparisons(strat_eq, bench_eq_full, bh_eq_full)

            if _bool(get("SAVE_METRICS"), True):
                out_csv = write_metrics_csv(
                    run_id, sym, CONFIG, m, params,
                    out_dir=get("CSV_DIR"),
                    extras=extras
                )

            # Merge buy & hold comparison metrics into m for database storage
            m_with_comparisons = {**m, **extras}

            # Serialize equity curve and events for tearsheet generation
            equity_json = None
            events_json = None
            buyhold_json = None
            if db_file:
                # Convert equity series to JSON
                strat_eq.name = f"{sym} Strategy"
                equity_json = strat_eq.to_json(orient='split', date_format='iso')
                # Convert buy & hold equity to JSON (only if enabled)
                if bh_eq_full is not None:
                    buyhold_json = bh_eq_full.to_json(orient='split', date_format='iso')
                # Convert events list to JSON if exists
                if events:
                    events_json = json.dumps(events, default=str)
                
                bt_db.insert_strategy_metrics(
                    db_file, run_id, sym, params, m_with_comparisons,
                    equity_json=equity_json,
                    events_json=events_json,
                    buyhold_json=buyhold_json
                )

            recs.append((m, params, strat_eq, res.get("events")))

    if _bool(get("SAVE_METRICS"), True) and out_csv:
        print(f"Metrics saved -> {out_csv}")

    if get("SAVE_DB", False) and 'db_file' in locals() and db_file:
        from backtester.db import finalize_run
        finalize_run(db_file, run_id)


if __name__ == "__main__":
    main()